version: "3"

services:
  flask_app:
    build: ./backend
    expose:
      - 5000
    environment:
      - APP_CODE=Flask-1458
    networks:
      - main

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - flask_app:flask_app   # allows nginx to communicate with flask_app using hostname flask_app
    depends_on:
      - flask_app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main

networks:
  main:
    driver: bridge
